runtime: go
api_version: go1

handlers:

        - url: /querycx
          script: _go_app
        - url: /
          static_files: dist/index.html
          upload: dist/(.*\.html)
        - url: /(.*\.(js|png|css))$
          static_files: dist/\1
          upload: dist/.*\.(js|png|css)$


skip_files:
        - ^e2e$
        - ^node_modules$
        - ^src$

default_expiration: "30d"

